# Path that contains bin/arm-none-eabi-gcc  (no need for /bin at the end)
GNU_INSTALL_ROOT := /usr
# ‘arm-none-eabi-gcc --version’ first line gives you this
GNU_VERSION := 13.2.1
# Executable prefix
GNU_PREFIX := arm-none-eabi
